# imports

In [8]:
import numpy as numpy
import pandas as pd

# load data

In [9]:
# src : https://www.kaggle.com/datasets/jahaidulislam/car-specification-dataset-1945-2020?select=Car+Dataset+1945-2020.csv
df = pd.read_csv("res/car-dataset-1945-2020.csv")
df

/var/folders/_k/5bp3r4wn3nsg0f47hdyhwrhr0000gn/T/ipykernel_99323/1849661473.py:2: DtypeWarning: Columns (0: load_height_mm, 1: length_mm, 2: width_mm, 3: height_mm, 4: wheelbase_mm, 5: front_track_mm, 6: rear_track_mm, 7: curb_weight_kg, 8: ground_clearance_mm, 9: trailer_load_with_brakes_kg, 10: clearance_mm, 11: max_trunk_capacity_l, 12: cargo_volume_m3, 13: overhead_camshaft, 14: cylinder_bore_and_stroke_cycle_mm, 15: turnover_of_maximum_torque_rpm, 16: capacity_cm3, 17: engine_hp_rpm, 18: bore_stroke_ratio, 19: steering_type, 20: battery_capacity_KW_per_h, 21: charging_time_h) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("res/car-dataset-1945-2020.csv")

,id_trim,Make,Modle,Generation,Year_from,Year_to,Series,Trim,Body_type,load_height_mm,...,front_suspension,steering_type,car_class,country_of_origin,number_of_doors,safety_assessment,rating_name,battery_capacity_KW_per_h,electric_range_km,charging_time_h
0,1,AC,ACE,1 generation,1993.0,2000.0,Cabriolet,3.5 MT,Cabriolet,NaN,...,Helical springs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,AC,ACE,1 generation,1993.0,2000.0,Cabriolet,4.6 MT,Cabriolet,NaN,...,Helical springs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,AC,ACE,1 generation,1993.0,2000.0,Cabriolet,4.9 AT,Cabriolet,NaN,...,Helical springs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,AC,ACE,1 generation,1993.0,2000.0,Roadster,2.9 AT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,AC,ACE,1 generation,1993.0,2000.0,Roadster,2.9 MT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70818,70983,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,2.4 AT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70819,70984,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,2.4 MT,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70820,70985,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,2.4 MT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70821,70986,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,3.2 AT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70822,70987,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,3.2 MT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN

# preprocessing

In [16]:
# Remove unnecessary columns and rename selected columns

columns_to_keep = [
    # Main
    "Make",
    "Modle",
    "Year_from",
    "Year_to",
    "Body_type",
    "car_class",
    "number_of_seats",

    # Engine
    "engine_type",
    "capacity_cm3",
    "engine_hp",
    "maximum_torque_n_m",
    "number_of_cylinders",
    "cylinder_layout",

    # Weight
    "curb_weight_kg",

    # Consumption
    "mixed_fuel_consumption_per_100_km_l",
    "city_fuel_per_100km_l",
    "highway_fuel_per_100km_l",
    "CO2_emissions_g/km",
    "emission_standards",
    "range_km",
    "fuel_grade",

    # Performance
    "acceleration_0_100_km/h_s",
    "max_speed_km_per_h",
]

df = df.loc[:, columns_to_keep].rename(
    columns={
        "Make": "manufacturer",
        "Modle": "model",
        "Year_from": "year_from",
        "Year_to": "year_to",
        "Body_type": "body_type",
        "car_class": "car_class",
        "CO2_emissions_g/km": "co2_emissions_g_per_km",
        "acceleration_0_100_km/h_s": "acceleration_0_100_km_h_s",
    }
)

df

,manufacturer,model,year_from,year_to,body_type,car_class,number_of_seats,engine_type,capacity_cm3,engine_hp,...,curb_weight_kg,mixed_fuel_consumption_per_100_km_l,city_fuel_per_100km_l,highway_fuel_per_100km_l,co2_emissions_g_per_km,emission_standards,range_km,fuel_grade,acceleration_0_100_km_h_s,max_speed_km_per_h
0,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2,Gasoline,3505.0,354.0,...,1510.0,NaN,20.0,9.0,NaN,NaN,"450|1,000",95,5.0,250
1,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2,Gasoline,4601.0,326.0,...,1510.0,NaN,15.0,10.0,NaN,NaN,600|900,98,5.0,250
2,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2,Gasoline,4942.0,260.0,...,1440.0,8.0,NaN,NaN,NaN,NaN,NaN,95,NaN,225
3,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70818,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70819,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70820,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70821,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70822,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# TODO : check missing values -> plot